name: inboxinsight
description: InboxInsight - Smart SMS Digest (Flutter prototype)
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lottie: ^2.3.0
  provider: ^6.0.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/mock_sms.json
    - assets/animations/ai_brain.json
    - assets/icons/bill.png
    - assets/icons/offer.png
    - assets/icons/service.png
    - assets/icons/telecom.png
